### ISSUE TITLE
Peer review #1

### ISSUE THREAD

**Issue by kbjakex** [Cloudperry/the-witness-puzzle-maker#1]
### Peer review

Hi! Fun idea for a project. I unfortunately could not test the code, because following the instructions got me this error:
<details>
<summary>Error (click to expand)</summary>

```console
kbjakex:~$ choosenim devel
Downloading Nim latest-devel from GitHub
[##################################################] 100.0% 0kb/s
 Extracting linux_x64.tar.xz
 Extracting linux_x64.tar
    Setting up git repository
   Building Nim #devel
  Compiler: Already built
   Switched to Nim #devel
kbjakex:~$ cd temp
kbjakex:~/temp$ nimble install https://github.com/Cloudperry/the-witness-puzzle-maker

Downloading https://github.com/Cloudperry/the-witness-puzzle-maker using git
  Verifying dependencies for theWitnessPuzzles@0.1.0
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer:  Installing cligen@1.5.28
    Prompt: cligen not found in any local packages.json, check internet for updated packages? [y/N]
y
    Answer: Downloading Official package list
    Success Package list downloaded.
       Tip: 6 messages have been suppressed, use --verbose to show them.
     Error: Package not found.
```

</details>

(This was on the fuksilaptop, which at the time of writing I no longer have access to due to forgetting my charger to the campus yesterday. I'm now on a Mac, and now the choosenim installer fails, seemingly because of C compilation errors, which is probably because the Mac is outdated in every way imaginable (13 years old). Sorry I wasn't able to test this.)

Having browsed the code, it's pretty clear you've programmed before. Not a whole lot to say.
* Code coverage is great!
* Code is certainly readable (at least with my Rust/C/C++/Java background), but also,
* I appreciate the comments for the more obscure syntactical features, such as * exporting to other modules. in retrospect I wish I'd done this as well. I'd still perhaps appreciate more comments on fields such as those in Level (pointGraph/cellGraph/pointData/cellData?) though, to get the basic idea
* Code has been split up appropriately to multiple files
* If there's one thing I'm a bit uncertain it's the Graph structure. 
  * The genericity itself isn't an issue, but it's being parameterized with `float`, `Point2D` and even `seq`, and the generic type is used as a key to a hash table. Floats are typically a poor choice for a hash map key because of floating-point imprecision (e.g. the typical `0.1 + 0.2 != 0.3` example), and `seq` as an array is heavy to hash / compare for equality (and in this case it's even a seq of Point2Ds). If at all possible, consider if you can find a way to use integers as keys (sometimes you can generate unique ids for objects and use those as keys, but in this case, since the problem as I understand it is largely on a grid, can you use a grid index?)
  * If keys were indeed to be flattened to ints, you could try to reduce the heavy nested hash collection structure to `seq[seq[N]]` or similar, assuming your keys are dense. I admit my understanding of the codebase is not good enough to be able to tell if this is viable, though.
* For fast insertions / removals when order doesn't matter, instead of a hash set, consider using a "bag"? Bag as in basically `seq`, but instead of an order-preserving remove(), you instead remove by swapping the to-be-removed element with the last element, and then remove the last element, which is a trivial O(1) operation. Hash sets are memory-heavy and are a poor fit for iteration over the data, and it seems a fast contains() isn't necessarily needed here? Bags are dense in memory (good iteration performance), have no memory overhead and have O(1) insert/remove
* Raylib 👍 

I had only heard of Nim until now, and I certainly enjoyed peeking into this world. The syntax is quite elegant in many ways, very concise without sacrificing legibility. It's unfortunate my codebase leaves such a bad impression of Rust, in contrast.

Last up: you've done a lot, but seems like you have a fair amount to do still, especially on the editor front. Not too many weeks left, so best of luck. Certainly more ambitious a project than mine.

(Project was downloaded on Fri, October 7th at 1:30 PM)

**Comment by Cloudperry** [comment]
> Hi! Fun idea for a project. I unfortunately could not test the code, because following the instructions got me this error:

I updated the install instructions and it should work now on Linux and Windows. You probably pressed enter instead of y and enter when Nimble asked about downloading packages.json (Nim's package manager uses json for the global package list :D). Tried to make Mac OS work as well, but there is something weird with the Raylib bindings I'm using and it didn't compile for me on a Mac (even tho the bindings mention Mac being supported).

> - If there's one thing I'm a bit uncertain it's the Graph structure.
>   - The genericity itself isn't an issue, but it's being parameterized with float, Point2D and even seq, and the generic type is used as a key to a hash table. Floats are typically a poor choice for a hash map key because of floating-point imprecision (e.g. the typical 0.1 + 0.2 != 0.3 example), and seq as an array is heavy to hash / compare for equality (and in this case it's even a seq of Point2Ds). If at all possible, consider if you can find a way to use integers as keys (sometimes you can generate unique ids for objects and use those as keys, but in this case, since the problem as I understand it is largely on a grid, can you use a grid index?)
>   - If keys were indeed to be flattened to ints, you could try to reduce the heavy nested hash collection structure to seq[seq[N]] or similar, assuming your keys are dense. I admit my understanding of the codebase is not good enough to be able to tell if this is viable, though.

Yeah good points about the adjacency list structure. Hash sets and hash tables being memory hungry really shows in the level file sizes. My example level which is an empty 5x5 level was 120+ kb when serialized to binary. After writing this I got it down to 26 kb (see edits at the bottom). ~~I will probably switch the adjacency list to be Table[N, Deque[N]], where [Deque](https://nim-lang.org/docs/deques.html) is the closest thing in Nim to the Bags u described.~~ The Graph[seq[Point2D]] in levels.nim is used to save the vertices of the maze "cells" where puzzle symbols can be. I will add some comments to the level format. Using floats as coordinates for the maze points is actually a deliberate decision, because I want to be able to support weird mazes like this (probably not during this course).
 ![](https://oyster.ignimgs.com/mediawiki/apis.ign.com/the-witness/0/09/Desert_Ruins_1.jpg?width=640) 
Another benefit of float coordinates is that the "endpoints" or goals of the maze can be represented as normal points a bit outside the maze grid and they are not a special case. For example in the test level I have represented the goal as the point (3.0, 4.25). Equality isn't a problem as I won't do arithmetics on the floats in the graph. Btw Nim's seqs are basically a replacement for Python lists or variable length arrays in other languages. Nim's arrays need to have their size known at compile time.

> Last up: you've done a lot, but seems like you have a fair amount to do still, especially on the editor front. Not too many weeks left, so best of luck. Certainly more ambitious a project than mine.

Thanks. Yeah I have already spent a bit of time on things that are probably not that relevant for this course. For example the levels should already scale very nicely to any display resolutions. Now I'm going to add some of the missing graphics elements. After that I can start making a simple level editor and implementing the actual game mechanics.

I didn't have time to do the peer review for your project, but I will do it before monday. Maybe I will join your discord as well. I'm interested in game development and low-level graphics programming too (right now I just know a bit of OpenGL basics).

Edit: I realized now that I can't switch the hash tables or hash sets without switching from ints to floats. That is because with float coordinates a specific node can't be found in a seq/bag just by index. Too late to switch floats to ints now.
Edit 2: I was able to get the test level size down to 26 kb (on disk) and 200 bytes (in memory) by changing the initial size of the graph neighbors hash set down to 4. Could be reduced further by changing the hash table initial size as well, but its a bit clumsy to do in Nim currently.

**Comment by kbjakex** [comment]
> You probably pressed enter instead of y and enter when Nimble asked about downloading packages.json

I did actually enter `y`, as shown in the output :) But in hindsight I should've probably re-run with the `--verbose` flag to see what was suppressed.

> Maybe I will join your discord as well. I'm interested in game development and low-level graphics programming too (right now I just know a bit of OpenGL basics).

It's not my server - I just wanted that I'd be found through a server rather than by adding as a friend, because I get too many spam friend requests to be able to distinguish from real ones and therefore routinely ignore those. In any case, for graphics programming, I can veeery much recommend [this server](https://discord.gg/6mgNGk7). I might be able to help as well, I have some OpenGL and Vulkan background myself, so feel free to hit me up.

> Using floats as coordinates for the maze points is actually a deliberate decision, because I want to be able to support weird mazes like this (probably not during this course).

I see. I'm still not sure I agree this is the best way - I'd be inclined to limit the use of floats to rendering purposes only, and try to keep nodes positionless elsewhere, but I don't have the time to dig into the project again right now to really suggest anything.

> Hash sets and hash tables being memory hungry really shows in the level file sizes.
> Edit 2: I was able to get the test level size down to 26 kb (on disk) and 200 bytes (in memory) by changing the initial size of the graph neighbors hash set down to 4. Could be reduced further by changing the hash table initial size as well, but its a bit clumsy to do in Nim currently.

If you really care about the binary size, you don't want it to depend on the in-RAM containers / representation used at all. Keys don't really need to be stored, for one, and any padding bytes & spare capacity can be eliminated. Even 26kb sounds suspiciously large, but also, I myself wouldn't dare to spend time on this until the project is otherwise done :^)
