### ISSUE TITLE
Peer review #2

### ISSUE THREAD

**Issue by ronituohino** [Cloudperry/the-witness-puzzle-maker#2]
Hello @Cloudperry!

I was excited to open your project since I've played The Witness before.
This was a cool opportunity to see some Nim, since I've only heard of it previously!

## Environment

I am using Zorin OS (Ubuntu clone) and the latest Nim installation according to your guide.  
It seems to be working!

I downloaded the project on the 13th of October at 11:18.

I used the latest git commit 9be1573.

### What did I do?

- Read through the docs
- Go through Linux installation
- Build project
- Run game
  - When not setting the level as a cli argument it doesn't seem to open with testLevel / testLevel.bin -> seems that it needs a full path to the file
  - Also the program screws a bit with my screen settings: it set my resolution at 1280x720 at the lowest refresh rate possible :joy:
- Run editor
- Start going through code

### Experience

Setup was really smooth and running the program went quite well.  

The main problem right now (even though you've done a lot) is that there isn't much functionality.

Personally, to avoid a crunch, I would cut some stuff out to focus on the most important features in terms of the course for now:
- leave the editor in the shadow and focus on the game and checking algorithms
- implement the most interesting tiles like Squares and Blocks, but forget about stuff like Jacks

## Code

I was unable to find parts which to criticise taking into consideration the previous peer review.

- I liked the NIMNOTE stuff to get more into Nim
- Project structure is good
- Code is really well commented and readable
- Consistent with Nim style guide
- Test coverage is good
- Unit tests are good

## Summary

The code is really good! However, the current state of the app is really unfinished: I hope that you can get at least some functionality done before the end of the course. Good luck!

**Comment by Cloudperry** [comment]
Hello. Very nice to have someone who knows The witness review this project. 
> The main problem right now (even though you've done a lot) is that there isn't much functionality.<br>
Personally, to avoid a crunch, I would cut some stuff out to focus on the most important features in terms of the course for now:
> - leave the editor in the shadow and focus on the game and checking algorithms
> - implement the most interesting tiles like Squares and Blocks, but forget about stuff like Jacks

Yeah as soon as I wrote some helper functions in levels.nim, making levels in code was pretty easy. After that I decided to cut the editor for now. I think I will try to do all the puzzle symbols, except for maybe the hollow blocks. That is because I'm not sure if Knuth's algorithm X will work for those. Jacks will be easy to implement. I have already done some basic player line logic and levels with only hexagons work already (not pushed to git yet).

> The code is really good! However, the current state of the app is really unfinished: I hope that you can get at least some functionality done before the end of the course. Good luck!

Thanks! I think I'll get every symbol other than blocks implemented pretty quickly, because I have planned the implementation quite far already. Somehow I always choose a gigantic project and get into crunch territory a bit like happened on my [last course project](https://github.com/Cloudperry/ultimate-tic-tac-toe). :D
